### ISSUE TITLE
Current ViT implementation works with timm 0.6.12 and not with 0.9.2

### ISSUE THREAD

**Issue by prakhar6sharma** [aditya-grover/climate-learn#102]
**Describe the bug**
Running `pytest tests/` gives an error for [`test_vit()`](https://github.com/aditya-grover/climate-learn/blob/e37183bf83b21d7788272b02ca0213b842f0e2b7/tests/models/instantiate_models_test.py#L5) when running with the version `0.9.2` but works perfectly with version `0.6.12`.

**To Reproduce**
Create a fresh conda environment with python 3.7 and install all the dependencies.

**Screenshots**
![Screenshot 2023-05-15 at 5 51 55 AM](https://github.com/aditya-grover/climate-learn/assets/37648724/bb5f1b83-7a65-4c2f-b22c-2111349952ca)

**Comment by jasonjewik** [comment]
I was able to reproduce this bug. I need to re-assess ViT anyway to make it conform with the rest of the updated models, so I'll update it to use the latest version of timm and then peg timm to version 0.9.2 in `pyproject.toml`.

**Comment by prakhar6sharma** [comment]
@jasonjewik, I have PRs (#101  and #103) failing in their build because of this issue.
