### ISSUE TITLE
Statistical Downscaling of other ERA5 Variables

### ISSUE THREAD

**Issue by jovidsilva** [aditya-grover/climate-learn#106]
So I am attempting to downscale ERA5 Sea Surface Temperature Variable, I was following along your tutorial at NeurIPS2022 CCAI. I noticed there you used 5 degree and 2 Degree Resolutions for 2m_temperature, Why is this done? It is not very clear. For Sea Surface Temperature i have data at 0.25 Degree resolution, but do i need a Coarser resolution to get this code to work for my chosen variable?

**Comment by jasonjewik** [comment]
Hi @jovidsilva, thank you for raising this issue. In the quickstart notebook, we downscale from 5 degree to 2 degree resolution for two reasons: (1) those are the available resolutions of [WeatherBench](https://github.com/pangeo-data/WeatherBench), the data source we use for the notebook, and (2) higher resolution data requires more time to download and more space to store. The primary aim of our quickstart is to show interested users how to make the code work relatively quickly, even if the particular resolutions are not very practical.

That being said, if you have sea surface temperature data at 0.25 degree resolution, that is great! We would love it if you used ClimateLearn to test out deep learning methods for such a problem setup. For the version of the code in our NeurIPS 2022 tutorial, it is rather difficult for users to integrate their own datasets. But, we have been making changes to ClimateLearn recently that should make it easier to do this. When these changes are complete and the documentation/tutorial is updated, I will let you know here. In the meantime, if you have further questions or matters we can assist you with, please do not hesitate to ask.

**Comment by jovidsilva** [comment]
Hi Jason,

Thanks for the quick clarification. I'm presently a post doctoral
researcher and data scientist working at CSIR - NIO. Our research is
primarily on the oceans and the sea surface temperature is one such
variable that we would like downscale to the Indian Ocean. Presently we do
this using Physical model downscaled with local forcings. However we would
like to compare these with ML based downscaling options. At present is
there any option to directly downscale ERA5 sea surface temperature to less
that 2 degree using the package?

**Comment by jasonjewik** [comment]
Yes, that is possible, but we have not done it ourselves yet.
