### ISSUE TITLE
Question Regarding Bilinear Interpolation for Downscaling before DL models

### ISSUE THREAD

**Issue by Escape142** [aditya-grover/climate-learn#121]
Hello,

I've noticed the use of bilinear interpolation for downscaling climate data in `loaders.py` [here](https://github.com/aditya-grover/climate-learn/blob/b48fb0242acc47e365af86bfbd9dd86e9dcbd6d2/src/climate_learn/utils/loaders.py#L340C13-L342C14). Given the complexity of climate data, I'm curious about this choice.

Could you share the rationale behind using bilinear interpolation? 

Thank you in advance.

**Comment by tung-nd** [comment]
We only perform bilinear interpolation before feeding it to the DL model. This is a common practice. The idea is that the DL will learn to fix the error of bilinear interpolation

**Comment by Escape142** [comment]
Thank you for your reply!

Can you clarify why did you use exactly 16 shards [here](https://github.com/aditya-grover/climate-learn/blob/b48fb0242acc47e365af86bfbd9dd86e9dcbd6d2/src/climate_learn/data/processing/nc2npz.py#L19C1-L19C23)?

**Comment by tung-nd** [comment]
so each shard is a collection of data we load to memory at once. If you increase the shard size you will have to read the data from disk less but each read will take longer, and vice versa. We found 16 to provide a good balance

**Comment by Escape142** [comment]
Could you please specify the sources for the land-sea mask and orography constant fields necessary to replicate the results presented in the paper?

**Comment by tung-nd** [comment]
Can you check this https://huggingface.co/datasets/jasonjewik/climate-learn/tree/main/weatherbench/era5/5.625deg

**Comment by Escape142** [comment]
Thank you!

According to the paper, ClimaX was supposed to be incorporated into ClimateLearn. However, it appears to be missing at the moment. Is my understanding correct?

**Comment by tung-nd** [comment]
It's not been pushed to the main branch. You can checkout the `tung_exps` branch which has the climax implementation
