### ISSUE TITLE
Climate-learn should have jupyter as a dependency

### ISSUE THREAD

**Issue by prakhar6sharma** [aditya-grover/climate-learn#34]
The `climate_learn.data.DataModule` uses `tqdm` to display progress when loading the dataset.

Unfortunately, it requires `Jupyter` and `ipywidgets` as a dependency. Otherwise it throws an error. 

Screenshot of error attached below.
![Screenshot 2023-01-29 at 4 20 05 PM](https://user-images.githubusercontent.com/37648724/215364662-30510fb2-be38-4d21-8a00-fe87c88d450a.png)

I have also added the snippet of code which I tried to run as a reference.

    from climate_learn.utils.datetime import Year, Days, Hours
    from climate_learn.data import DataModule

    def main():

        data_module = DataModule(
            dataset = "ERA5",
            task = "forecasting",
            root_dir = "/data0/datasets/weatherbench/data/weatherbench/era5/5.625deg/",
            in_vars = ["2m_temperature"],
            out_vars = ["2m_temperature"],
            train_start_year = Year(2005),
            val_start_year = Year(2015),
            test_start_year = Year(2016),
            end_year = Year(2016),
            pred_range = Days(3),
            subsample = Hours(6),
            batch_size = 128,
            num_workers = 1
        )

    if __name__ == "__main__":
        main()

This issue is resolved by running `pip install jupyter`.

**Comment by prakhar6sharma** [comment]
Also, the progress bar doesn't show any progress. 
Not sure if that is because of the `Jupyter` and `ipywidgets` version.

Attaching screenshot of the behavior.
![Screenshot 2023-01-29 at 4 29 56 PM](https://user-images.githubusercontent.com/37648724/215365194-43d0f18a-47b0-44e0-8431-0d42294b4fb2.png)

**Comment by jasonjewik** [comment]
Hi, @prakhar6sharma can you try the code in #35? Rather than adding jupyter as a dependency, I changed the tqdm import. Let me know if the linked PR resolves your issue.

**Comment by prakhar6sharma** [comment]
Thanks @jasonjewik. I have tested it with a fresh environment and can confirm that it works.
