### ISSUE TITLE
Refactoring of climate_learn.models.load_model to support clean integration with LightningCLI

### ISSUE THREAD

**Issue by prakhar6sharma** [aditya-grover/climate-learn#37]
Hi,

The current way to do forecasting and downscaling involves creating a[ `DataModule`](https://github.com/aditya-grover/climate-learn/blob/5ce3dc9660f19d1802b222ccbc31cbccccfc9201/src/climate_learn/data/module.py#L17) and calling [`load_model`](https://github.com/aditya-grover/climate-learn/blob/5ce3dc9660f19d1802b222ccbc31cbccccfc9201/src/climate_learn/models/__init__.py#L5) which are then passed on to the trainer. The former is inherited from LightningDataModule whereas the later is a function that returns a LightningModule.

For reproducibility purposes and clear distinction between source code and hyper-parameters, I believe refactoring to the `load_model` should be done.

By refactoring, I mean `load_model`should be converted to class that is inherited from `pl.LightningModule` and we can then use something like LightningCLI (Similar use case shown in the [docs](https://pytorch-lightning.readthedocs.io/en/stable/cli/lightning_cli_intermediate_2.html)).

This way via YAML only, one can control which class of model, datamodule, etc should be created for a given experiment.

**Comment by prakhar6sharma** [comment]
Would love to hear @tung-nd's opinion about this feature request.

**Comment by jasonjewik** [comment]
I agree with you. More broadly, refactoring our model code (not just the `load_model` function) is on my to-do list for ClimateLearn. Currently no ETC on this, though. I will update you when I start working on the refactor.

**Comment by prakhar6sharma** [comment]
I can help in drafting the PR for this and ask for your review.

**Comment by aditya-grover** [comment]
That would be great. Thanks Prakhar!
