### ISSUE TITLE
Support for IterableDataset

### ISSUE THREAD

**Issue by prakhar6sharma** [aditya-grover/climate-learn#38]
Hi,

Currently the [`ERA5`](https://github.com/aditya-grover/climate-learn/blob/5ce3dc9660f19d1802b222ccbc31cbccccfc9201/src/climate_learn/data/modules/era5_module.py#L19) class is inherited from the `torch.utils.data.dataset`.

For tasks involving a lot of input and output variables, it becomes impossible to load them all in the RAM at the same time. Hence, I was wondering if there would be a support for [`IterableDataset`](https://pytorch.org/docs/stable/data.html#iterable-style-datasets). It would support loading only a subpart of the data in the RAM.

**Comment by prakhar6sharma** [comment]
@tung-nd has worked on something similar for ERA5. His opinion about this request would be highly valuable.

**Comment by jasonjewik** [comment]
Yes, for the reasons you point out, it would be more practical if we switch to using pytorch's `IterableDataset`. I am currently working on a refactor of our data code, and this switch is one of the things I'm working on.

I'm also considering using [TorchData](https://github.com/pytorch/data), but the project is still in beta, so I'm hesitant to do so at this time.

**Comment by tung-nd** [comment]
I tried DataPipes once but failed so I would suggest using IterableDataset for now

**Comment by jasonjewik** [comment]
OK. I'll stick with `IterableDataset`. Leaving this issue open until I implement this in the refactor.
