### ISSUE TITLE
Some ideas on how to restructure the data handling of the Climate-learn 

### ISSUE THREAD

**Issue by prakhar6sharma** [aditya-grover/climate-learn#43]
Hi,

To add support for #38 in the current code, it can become quite messy as the dataset source class and task class (eg forecasting) are somewhat [coupled](https://github.com/aditya-grover/climate-learn/blob/b350f39a8f0f162fd5a8901518f2a35c1681a525/src/climate_learn/data/modules/era5_module.py#L98) As a result, to add support for either of new dataset source, task, or data-loading strategy would involve creating loads of new classes and writing redundant code. 

To solve this, I believe that the source dataset class, task specific class, and data-loading strategy class (eg IterableDataset) should be decoupled.

I tried to formalize this as requirements that a good implementation/refactor should follow.

1. [`DataModule`](https://github.com/aditya-grover/climate-learn/blob/b350f39a8f0f162fd5a8901518f2a35c1681a525/src/climate_learn/data/module.py#L29) would act as an interface to the entire data handling. (DataModule is inherited from LightningDataModule)
2. To add a new task/combination of tasks (multitasking), one shouldn’t make change to the source dataset class (eg [`ERA5`](https://github.com/aditya-grover/climate-learn/blob/b350f39a8f0f162fd5a8901518f2a35c1681a525/src/climate_learn/data/modules/era5_module.py#L19)).
3. Writing the code for adding a new data source (eg CMIP6) for an already supported task (eg forecasting) should only involve writing the code for reading and preprocessing the new data source files.
4. To add support for new way of loading the dataset (eg map-style, streaming, [`corgipile`](https://github.com/aditya-grover/climate-learn/blob/b350f39a8f0f162fd5a8901518f2a35c1681a525/src/climate_learn/data/modules/era5_module.py#L19), etc), one should write code only for the loading strategy and it should be dataset agnostic.

Unfortunately, as of now I can't think of any structuring that satisfies all the requirements. Hence, I opened this as an issue here, hoping someone would chime in and share their thoughts on this.

**Comment by tung-nd** [comment]
The Iterdataset pull request hopefully has solved some of the structural concerns. We now have NpyReader to read data from files, Forecast and Downscale classes are designed to output data for each of the tasks, and DataModule handles the entire data handling

**Comment by jasonjewik** [comment]
Linking the Iterdataset PR for convenience: https://github.com/aditya-grover/climate-learn/pull/44.

However, Iterdataset is space-inefficient (doubles the amount of storage required). Perhaps we could look into CorgiPile:
- https://arxiv.org/pdf/2206.05830.pdf
- https://github.com/JerryLead/CorgiPile-PyTorch
