### ISSUE TITLE
inconsistency between tutorial notebook and resnet model

### ISSUE THREAD

**Issue by bulaienTang** [aditya-grover/climate-learn#52]
**Describe the bug**
"upsampling" removed in resnet kwargs but still being passed in NeurIPS2022_CCAI_Tutorial.ipynb

**To Reproduce**
run the downscaling section of NeurIPS2022_CCAI_Tutorial.ipynb

**Expected behavior**
the model should not accept "upsampling" as a parameter

**Screenshots**
<img width="1188" alt="Screenshot 2023-02-06 at 11 09 20 PM" src="https://user-images.githubusercontent.com/34512891/217403020-26925076-b9eb-416c-ae29-54c8e2f01903.png">

**Comment by tung-nd** [comment]
Please remove the upsampling parameter in the notebook, as it is no longer required. Detailed explanation here: https://github.com/aditya-grover/climate-learn/pull/44#issuecomment-1416638937

**Comment by bulaienTang** [comment]
Done.
