### ISSUE TITLE
dimension miss match between ground truth & pred for downscaling task

### ISSUE THREAD

**Issue by bulaienTang** [aditya-grover/climate-learn#54]
**Describe the bug**
During visualization of the downscaling task, there seems to be a mismatch in the dimension of pred and gt

**To Reproduce**
Simply run the NeurIPS2022_CCAI_Tutorial.ipynb or the Visualization.ipynb in the docs/notebooks of the tutorials-split branch

**Screenshots**
<img width="1446" alt="Screenshot 2023-02-07 at 10 32 49 PM" src="https://user-images.githubusercontent.com/34512891/217453392-6e9cb5cb-87a3-42af-b39e-510648b39e47.png">

**Comment by tung-nd** [comment]
This is because of the new way we do downscaling, where we first interpolate the input to match the output dimensions before feeding to the network. Detailed explanation here: https://github.com/aditya-grover/climate-learn/pull/44#issuecomment-1416638937
We should do the same for the visualization function, i.e., interpolate the input first before feeding it to the network. The interpolation function is at https://github.com/aditya-grover/climate-learn/blob/main/src/climate_learn/models/modules/downscale.py#L11

**Comment by bulaienTang** [comment]
So we do not interpolate for forecasting right?

**Comment by tung-nd** [comment]
actually, you can always use the interpolation function whether it is forecasting or downscaling, because if the input and expected output dimensions match, the function will leave the input intact, otherwise it will interpolate the input

**Comment by bulaienTang** [comment]
I see, but I'm still getting this shape not matching error in functional.interpolate function, for forecasting if I'm calling the interpolate_input function on x. 

<img width="978" alt="Screenshot 2023-02-08 at 5 37 04 PM" src="https://user-images.githubusercontent.com/34512891/217692847-ae29d6da-efed-4616-acdb-fe85366440ae.png">

**Comment by tung-nd** [comment]
ok, can you print the dimensions out to better understand where the bug comes from?

**Comment by bulaienTang** [comment]
Yes. So for forecasting, x, y have shape torch.Size([1, 1, 32, 64]) torch.Size([1, 32, 64]). for downscaling, x, y have shape torch.Size([1, 32, 64]) torch.Size([1, 64, 128]).
What I did is I added this `x = interpolate_input(x, y)` line in the visualize function
<img width="488" alt="Screenshot 2023-02-08 at 6 22 51 PM" src="https://user-images.githubusercontent.com/34512891/217701010-9f35ad36-b878-4120-b943-a61d46b63c65.png">

**Comment by bulaienTang** [comment]
Oh, the issue now is with the downscaling not forecasting, forecasting works fine, no bugs. 
Downscaling has this issue, please ignore the bug screenshot above
<img width="1170" alt="Screenshot 2023-02-08 at 6 29 43 PM" src="https://user-images.githubusercontent.com/34512891/217702145-55898bdc-043d-47d0-8edc-60a07274d232.png">

**Comment by tung-nd** [comment]
ok, now what you can do is print the shape of the tensors in forecasting (which is working) before the interpolation function to understand what the expected shape is, and fix the downscaling accordingly

**Comment by bulaienTang** [comment]
Fixed, created [pull request](https://github.com/aditya-grover/climate-learn/pull/57)
