### ISSUE TITLE
Possible bug in visualizing samples 

### ISSUE THREAD

**Issue by rutujagurav** [aditya-grover/climate-learn#71]
**Describe the bug**
`climate_learn.utils.visualize()` prints the image upside down and with flipped colormap. 

**To Reproduce**
I am merely running the demo notebook found here -  https://colab.research.google.com/drive/1WiNEK1BHsiGzo_bT9Fcm8lea2H_ghNfa

**Expected behavior**
I believe the map plots produced by `visualize()` should have the same orientation and colormap as the stock images provided in the above notebook i.e. northern hemisphere on top and in the red-blue colormap red should correspond to higher values and blue to lower.

**Screenshots**
![image](https://user-images.githubusercontent.com/14856287/220252982-2c590e92-afe5-47a0-8ee4-09b22012ad6d.png)

**Environment**
N/A
**Additional context**
N/A

**Comment by jasonjewik** [comment]
Hi @rutujagurav, thanks for bringing this to our attention. Can you check if #72 produces the behavior you expect? If you are using the tutorial notebook on Google Colab, you can install the library from this specific branch as:
```console
pip install git+https://github.com/aditya-grover/climate-learn.git@issue-71
```

**Comment by rutujagurav** [comment]
For future reference, looks like this change was merged into the main branch and issue-71 branch was deleted. You'll get the following error if you run the above command in the notebook.

```
WARNING: Did not find branch or tag 'issue-71', assuming revision or ref.
  Running command git checkout -q issue-71
  error: pathspec 'issue-71' did not match any file(s) known to git
ERROR: Command errored out with exit status 1: git checkout -q issue-71
```

Simply reinstall the main branch.
