### ISSUE TITLE
Efficient loading for ERA5 from netcdf using chunks

### ISSUE THREAD

**Issue by prakhar6sharma** [aditya-grover/climate-learn#76]
**Is your feature request related to a problem? Please describe.**
Currently, the iter approach first saves files into .npz chunks and then reloads them using NpyReader. 

**Describe the solution you'd like**
Instead of duplicating data into a .npz, can we read from the netcdf files without loading all of them into the memory at the same time. 

I don't know how to do this. Just creating it as an issue for now.

**Comment by jasonjewik** [comment]
I agree with you that the current solution for data loading is space-inefficient. 

I have done some experiments with loading directly from NetCDF4. Major issue is that you still have to convert from NetCDF4 format to PyTorch Tensors, which is a slow process. Introducing that much per-batch overhead could significantly slow down model training/evaluation. By comparison, the current method handles all the conversion upfront and then amortizes it over the cost of model training/evaluation.
