### ISSUE TITLE
Bug in the persistence baseline for forecasting

### ISSUE THREAD

**Issue by prakhar6sharma** [aditya-grover/climate-learn#83]
**Describe the bug**
The persistence baseline for forecasting assumes that the last input value can be used as output. But this makes the assumption that the input variables is same as output variables. See [this](https://github.com/aditya-grover/climate-learn/blob/f1523c5278a4bdb511dbf92bb32072995b5d6158/src/climate_learn/models/modules/forecast.py#L185).

**Comment by prakhar6sharma** [comment]
@tung-nd can you please confirm that it is indeed a bug and if possible come up with a follow-up PR.

In my personal opinion, I don't think we can support persistence baseline for the general case. Currently, data-loader doesn't make assumption the the set of output variables should be a subset of input variables.

**Comment by jasonjewik** [comment]
You're right. We are making too much of an assumption here. IMO we can make persistence baseline a toggle (_i.e._, the user specifies whether they want a persistence baseline to show up in the results AND we check that the output variables are a subset of the input variables).
