### ISSUE TITLE
Deterministic randomness in ShardDataset

### ISSUE THREAD

**Issue by prakhar6sharma** [aditya-grover/climate-learn#89]
**Is your feature request related to a problem? Please describe.**
Currently `ShardDataset`, implements `__iter__()` to build batch. Inside the `iter`, the order of data is determined by [`self.epoch`](https://github.com/aditya-grover/climate-learn/blob/d298a0b096f8c1bd2e339f34017300dc14ea4a54/src/climate_learn/data/dataset/shard_dataset.py#L309). Unfortunately, the `self.epoch` is incremented only for the child process and not for the parent process as a result, each epoch thus results in same shuffling order. 

**Describe the solution you'd like**
Having access to the `trainer` to retrieve epoch number or set up communication across child processes under the `__iter__()`.

**Comment by jasonjewik** [comment]
Could we do something using the Lightning Module hooks like [`on_train_epoch_start`](https://lightning.ai/docs/pytorch/stable/common/lightning_module.html#on-train-epoch-start)?
